"""auto add-vote

Revision ID: 0a62034214bc
Revises: 0b91cbe46509
Create Date: 2022-01-08 20:13:28.393685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a62034214bc'
down_revision = '0b91cbe46509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vote',
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('post_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['post_id'], ['posts.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('user_id', 'post_id')
                    )
    op.add_column('posts', sa.Column('published', sa.Boolean(),
                  server_default='True', nullable=False))
    op.drop_column('posts', 'pulished')
    # ### end Alembic commands ###
    # Looks like the 'pulished' columns was previously spelled incorrectly...


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('pulished', sa.BOOLEAN(
    ), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('posts', 'published')
    op.drop_table('vote')
    # ### end Alembic commands ###
